version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auction

  supply:
    build:
      context: ./supply
    ports:
      - "8080:8080"
    depends_on:
      - db

  demand:
    build:
      context: ./demand
    ports:
      - "8081:8081"
    depends_on:
      - db
